# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt
[character]
success_symbol = "\\$"
error_symbol = "[\\$](red)"
vicmd_symbol = "&"

# The line_break module separates the prompt into two lines.
[line_break]
disabled = true

[username]
format = "[$user]($style)"
style_user = "bold blue"
show_always = true

[hostname]
format =  "@[$hostname]($style) "
style = "bold grey"
ssh_only = false
disabled = false

[directory]
truncation_length = 5

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
disabled = true

[golang]
disabled = true
