# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt
[character]
success_symbol = "\\$"
error_symbol = "[\\$](red)"
vicmd_symbol = "&"

# The line_break module separates the prompt into two lines.
[line_break]
disabled = true

[username]
format = "[$user]($style)"
style_user = "bold blue"
show_always = true

[hostname]
format =  "@[$hostname]($style) "
style = "bold grey"
ssh_only = false
disabled = false

[directory]
truncation_length = 5

# Disable the package module, hiding it from the prompt completely
[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "yellow"

[package]
disabled = true

[aws]
disabled = true

[docker_context]
disabled = true

[bun]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[golang]
disabled = true

[lua]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[gcloud]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true
