theme = "native"
icons = "awesome"

[[block]]
block = "net"
on_click = "alacritty -e zsh -c \"nmcli device wifi list && nmcli device wifi connect --ask\""
device = "wlan0"
format = "{ssid} ({signal_strength}) {ip}"
interval = 5

[[block]]
block = "cpu"
interval = 1

#[[block]]
#block = "sound"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "time"
interval = 5
format = "%a %Y-%m-%d %R"
